"""empty message

Revision ID: 3aab2e961996
Revises: b2f6c59332ae
Create Date: 2019-12-13 05:41:20.133252

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3aab2e961996'
down_revision = 'b2f6c59332ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'slug',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=128),
               nullable=True)
    op.alter_column('tag', 'slug',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tag', 'slug',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=128),
               nullable=False)
    op.alter_column('post', 'slug',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=128),
               nullable=False)
    # ### end Alembic commands ###
